name: AdvancedWoodcutter
version: ${project.version}
main: fr.gohansword.advancedwoodcutter.AdvancedWoodcutter
api-version: 1.16
commands:
  woodmenu:
    description: open the main menu
    aliases: [wm]
